name: raia_rgon
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  modal_progress_hud: ^0.1.3
  provider: any
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/icons/
   - images/jackets/
   - images/trousers/
   - images/shoes/
   - images/t_shirts/


#  fonts:
#    - family: ShadowsIntoLight-Regular
#      fonts:
#        - asset: fonts/ShadowsIntoLight-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
